name: Build APK

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Build Android APK
      uses: KPCOFGS/android-builder@v2
      with:
        path: android
        build-tools: 33.0.2
        java: 17
    
    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: Arian-Jojo-VPN
        path: android/app/build/outputs/apk/release/*.apk
